.TH "Net/NetInfoTest/src/port/MainWindow.py" 3 "NekoCollections" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Net/NetInfoTest/src/port/MainWindow.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBport\&.MainWindow\&.MainWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBport\fP"
.br
.ti -1c
.RI "namespace \fBport\&.MainWindow\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBport\&.MainWindow\&.find_column_index\fP (model, str column_name)"
.br
.ti -1c
.RI "\fBport\&.MainWindow\&.search_and_scroll\fP (table_view, str column_name, str target_value)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NekoCollections from the source code\&.
