.TH "port.MainWindow" 3 "NekoCollections" \" -*- nroff -*-
.ad l
.nh
.SH NAME
port.MainWindow
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBfind_column_index\fP (model, str column_name)"
.br
.ti -1c
.RI "\fBsearch_and_scroll\fP (table_view, str column_name, str target_value)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " int port\&.MainWindow\&.find_column_index ( model, str column_name)"

.PP
.nf
根据列名获取列索引
.fi
.PP
 
.PP
Definition at line \fB104\fP of file \fBMainWindow\&.py\fP\&.
.SS "port\&.MainWindow\&.search_and_scroll ( table_view, str column_name, str target_value)"

.PP
.nf
根据列名和值搜索并跳转
.fi
.PP
 
.PP
Definition at line \fB111\fP of file \fBMainWindow\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NekoCollections from the source code\&.
