.TH "port.PortScanner.PortScanner" 3 "NekoCollections" \" -*- nroff -*-
.ad l
.nh
.SH NAME
port.PortScanner.PortScanner
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBget_all_ports\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBPortScanner\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "port\&.PortScanner\&.PortScanner\&.get_all_ports ()\fR [static]\fP"

.PP
Definition at line \fB5\fP of file \fBPortScanner\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NekoCollections from the source code\&.
