.TH "port" 3 "NekoCollections" \" -*- nroff -*-
.ad l
.nh
.SH NAME
port
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBMainWindow\fP"
.br
.ti -1c
.RI "namespace \fBPortScanner\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "port\&.main ()"

.PP
Definition at line \fB10\fP of file \fB__init__\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NekoCollections from the source code\&.
