.TH "port.MainWindow.MainWindow" 3 "NekoCollections" \" -*- nroff -*-
.ad l
.nh
.SH NAME
port.MainWindow.MainWindow
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, parent=None)"
.br
.ti -1c
.RI "\fBinitializePage\fP (self)"
.br
.ti -1c
.RI "\fBinitializeData\fP (self)"
.br
.ti -1c
.RI "\fBinitializeConnections\fP (self)"
.br
.ti -1c
.RI "\fBappendRow\fP (self, dict[str, Any] rowData)"
.br
.ti -1c
.RI "\fBhandleData\fP (self)"
.br
.ti -1c
.RI "\fBsearchData\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBrootLayout\fP = QVBoxLayout(self)"
.br
.ti -1c
.RI "\fBsearchLayout\fP = QHBoxLayout(self)"
.br
.ti -1c
.RI "\fBsearchCombo\fP = QComboBox(self)"
.br
.ti -1c
.RI "\fBsearchLineEdit\fP = QLineEdit(self)"
.br
.ti -1c
.RI "\fBsearchButton\fP = QPushButton(self)"
.br
.ti -1c
.RI "\fBtableView\fP = QTableView(self)"
.br
.ti -1c
.RI "\fBbottomLayout\fP = QHBoxLayout(self)"
.br
.ti -1c
.RI "\fBbottomStartSearchButton\fP = QPushButton(self)"
.br
.ti -1c
.RI "\fBbottomStopSearchButton\fP = QPushButton(self)"
.br
.ti -1c
.RI "\fBmodel\fP = QStandardItemModel()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBMainWindow\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "port\&.MainWindow\&.MainWindow\&.__init__ ( self,  parent = \fRNone\fP)"

.PP
Definition at line \fB10\fP of file \fBMainWindow\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "port\&.MainWindow\&.MainWindow\&.appendRow ( self, dict[str,Any] rowData)"

.PP
Definition at line \fB74\fP of file \fBMainWindow\&.py\fP\&.
.SS "port\&.MainWindow\&.MainWindow\&.handleData ( self)"

.PP
Definition at line \fB89\fP of file \fBMainWindow\&.py\fP\&.
.SS "port\&.MainWindow\&.MainWindow\&.initializeConnections ( self)"

.PP
Definition at line \fB70\fP of file \fBMainWindow\&.py\fP\&.
.SS "port\&.MainWindow\&.MainWindow\&.initializeData ( self)"

.PP
Definition at line \fB40\fP of file \fBMainWindow\&.py\fP\&.
.SS "port\&.MainWindow\&.MainWindow\&.initializePage ( self)"

.PP
Definition at line \fB16\fP of file \fBMainWindow\&.py\fP\&.
.SS "port\&.MainWindow\&.MainWindow\&.searchData ( self)"

.PP
Definition at line \fB98\fP of file \fBMainWindow\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "port\&.MainWindow\&.MainWindow\&.bottomLayout = QHBoxLayout(self)"

.PP
Definition at line \fB33\fP of file \fBMainWindow\&.py\fP\&.
.SS "port\&.MainWindow\&.MainWindow\&.bottomStartSearchButton = QPushButton(self)"

.PP
Definition at line \fB34\fP of file \fBMainWindow\&.py\fP\&.
.SS "port\&.MainWindow\&.MainWindow\&.bottomStopSearchButton = QPushButton(self)"

.PP
Definition at line \fB35\fP of file \fBMainWindow\&.py\fP\&.
.SS "port\&.MainWindow\&.MainWindow\&.model = QStandardItemModel()"

.PP
Definition at line \fB55\fP of file \fBMainWindow\&.py\fP\&.
.SS "port\&.MainWindow\&.MainWindow\&.rootLayout = QVBoxLayout(self)"

.PP
Definition at line \fB18\fP of file \fBMainWindow\&.py\fP\&.
.SS "port\&.MainWindow\&.MainWindow\&.searchButton = QPushButton(self)"

.PP
Definition at line \fB23\fP of file \fBMainWindow\&.py\fP\&.
.SS "port\&.MainWindow\&.MainWindow\&.searchCombo = QComboBox(self)"

.PP
Definition at line \fB21\fP of file \fBMainWindow\&.py\fP\&.
.SS "port\&.MainWindow\&.MainWindow\&.searchLayout = QHBoxLayout(self)"

.PP
Definition at line \fB20\fP of file \fBMainWindow\&.py\fP\&.
.SS "port\&.MainWindow\&.MainWindow\&.searchLineEdit = QLineEdit(self)"

.PP
Definition at line \fB22\fP of file \fBMainWindow\&.py\fP\&.
.SS "port\&.MainWindow\&.MainWindow\&.tableView = QTableView(self)"

.PP
Definition at line \fB30\fP of file \fBMainWindow\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NekoCollections from the source code\&.
