.TH "port.PortScanner" 3 "NekoCollections" \" -*- nroff -*-
.ad l
.nh
.SH NAME
port.PortScanner
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPortScanner\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBdisplay_example\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "port\&.PortScanner\&.display_example ()"

.PP
Definition at line \fB29\fP of file \fBPortScanner\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NekoCollections from the source code\&.
